# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InfoCliente.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class info_cliente(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(317, 372)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.label = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout.addWidget(self.label)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_2)
        self.LEnom = QtGui.QLineEdit(self.centralwidget)
        self.LEnom.setObjectName(_fromUtf8("LEnom"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.LEnom)
        self.label_3 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.LabelRole, self.label_3)
        self.LEid = QtGui.QLineEdit(self.centralwidget)
        self.LEid.setObjectName(_fromUtf8("LEid"))
        self.formLayout.setWidget(1, QtGui.QFormLayout.FieldRole, self.LEid)
        self.label_4 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.LabelRole, self.label_4)
        self.LEpais = QtGui.QLineEdit(self.centralwidget)
        self.LEpais.setObjectName(_fromUtf8("LEpais"))
        self.formLayout.setWidget(2, QtGui.QFormLayout.FieldRole, self.LEpais)
        self.label_5 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.LabelRole, self.label_5)
        self.LEprov = QtGui.QLineEdit(self.centralwidget)
        self.LEprov.setObjectName(_fromUtf8("LEprov"))
        self.formLayout.setWidget(3, QtGui.QFormLayout.FieldRole, self.LEprov)
        self.label_7 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.LabelRole, self.label_7)
        self.LEciud = QtGui.QLineEdit(self.centralwidget)
        self.LEciud.setObjectName(_fromUtf8("LEciud"))
        self.formLayout.setWidget(4, QtGui.QFormLayout.FieldRole, self.LEciud)
        self.label_8 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.LabelRole, self.label_8)
        self.LEpost = QtGui.QLineEdit(self.centralwidget)
        self.LEpost.setObjectName(_fromUtf8("LEpost"))
        self.formLayout.setWidget(5, QtGui.QFormLayout.FieldRole, self.LEpost)
        self.label_6 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.LabelRole, self.label_6)
        self.LEmail = QtGui.QLineEdit(self.centralwidget)
        self.LEmail.setObjectName(_fromUtf8("LEmail"))
        self.formLayout.setWidget(6, QtGui.QFormLayout.FieldRole, self.LEmail)
        self.label_9 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.LabelRole, self.label_9)
        self.LEtarg = QtGui.QLineEdit(self.centralwidget)
        self.LEtarg.setObjectName(_fromUtf8("LEtarg"))
        self.formLayout.setWidget(7, QtGui.QFormLayout.FieldRole, self.LEtarg)
        self.label_10 = QtGui.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.LabelRole, self.label_10)
        self.LEpw = QtGui.QLineEdit(self.centralwidget)
        self.LEpw.setInputMask(_fromUtf8(""))
        self.LEpw.setEchoMode(QtGui.QLineEdit.Password)
        self.LEpw.setObjectName(_fromUtf8("LEpw"))
        self.formLayout.setWidget(8, QtGui.QFormLayout.FieldRole, self.LEpw)
        self.verticalLayout.addLayout(self.formLayout)
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.RBAE = QtGui.QRadioButton(self.centralwidget)
        self.RBAE.setObjectName(_fromUtf8("RBAE"))
        self.horizontalLayout.addWidget(self.RBAE)
        self.RBVisa = QtGui.QRadioButton(self.centralwidget)
        self.RBVisa.setObjectName(_fromUtf8("RBVisa"))
        self.horizontalLayout.addWidget(self.RBVisa)
        self.RBmaster = QtGui.QRadioButton(self.centralwidget)
        self.RBmaster.setObjectName(_fromUtf8("RBmaster"))
        self.horizontalLayout.addWidget(self.RBmaster)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.entrarbtn = QtGui.QPushButton(self.centralwidget)
        self.entrarbtn.setObjectName(_fromUtf8("entrarbtn"))
        self.verticalLayout.addWidget(self.entrarbtn)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Registro Cliente", None))
        self.label.setText(_translate("MainWindow", "Informacion General del cliente", None))
        self.label_2.setText(_translate("MainWindow", "Nombre", None))
        self.LEnom.setPlaceholderText(_translate("MainWindow", "Eje: Alberto Sibaja Vuelve", None))
        self.label_3.setText(_translate("MainWindow", "ID", None))
        self.LEid.setPlaceholderText(_translate("MainWindow", "Eje: 12364978", None))
        self.label_4.setText(_translate("MainWindow", "Pais", None))
        self.LEpais.setPlaceholderText(_translate("MainWindow", "Eje:Costa Rica", None))
        self.label_5.setText(_translate("MainWindow", "Estado/provincia", None))
        self.LEprov.setPlaceholderText(_translate("MainWindow", "Eje: Cartago", None))
        self.label_7.setText(_translate("MainWindow", "Ciudad", None))
        self.LEciud.setPlaceholderText(_translate("MainWindow", "Eje: Los Angeles", None))
        self.label_8.setText(_translate("MainWindow", "Cod. Postal", None))
        self.LEpost.setPlaceholderText(_translate("MainWindow", "Eje: 35955", None))
        self.label_6.setText(_translate("MainWindow", "Email", None))
        self.LEmail.setPlaceholderText(_translate("MainWindow", "Eje: albertsivu@mail.com", None))
        self.label_9.setText(_translate("MainWindow", "# Targeta", None))
        self.LEtarg.setPlaceholderText(_translate("MainWindow", "Eje: albertsivu@mail.com", None))
        self.label_10.setText(_translate("MainWindow", "Contraseña", None))
        self.LEpw.setPlaceholderText(_translate("MainWindow", "Eje: patito123", None))
        self.RBAE.setText(_translate("MainWindow", "American Express", None))
        self.RBVisa.setText(_translate("MainWindow", "Visa", None))
        self.RBmaster.setText(_translate("MainWindow", "Master Card", None))
        self.entrarbtn.setText(_translate("MainWindow", "Registrar", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = info_cliente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

